/** Galla design tokens — the single source is ../design/DESIGN-TOKENS.md.
 *  Components reference these names only; a raw hex in a component is a bug. */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        ink: "#111113",
        "text-2": "#77777C",
        "text-3": "#AEAEB2",
        chevron: "#C7C7CC",
        bg: "#F4F4F6",
        card: "#FFFFFF",
        separator: "#F0F0F2",
        "fill-2": "#EEEEF0",
        "fill-3": "#E9E9EB",
        sheet: "#F9F9FA",
        accent: "#0A6BE0",
        green: { DEFAULT: "#28934E", tint: "#EAF6EE" },
        amber: { DEFAULT: "#C97F0E", deep: "#9C6408", tint: "#FBF2E0" },
        red: { DEFAULT: "#D23B2E", tint: "#FCEDEB" },
        khata: { paper: "#FBFAF6", rule: "#EDE8DA", ink: "#4A463C" },
      },
      fontFamily: {
        sans: ["-apple-system", "BlinkMacSystemFont", "SF Pro Text", "Segoe UI",
               "Noto Sans", "Noto Sans Tamil", "sans-serif"],
      },
      fontSize: {
        // The type ramp from DESIGN-TOKENS.md, size + tracking together.
        verdict: ["46px", { lineHeight: "1", letterSpacing: "-2px" }],
        extracted: ["38px", { lineHeight: "1", letterSpacing: "-1.5px" }],
        screen: ["32px", { lineHeight: "1.05", letterSpacing: "-1.1px" }],
        gauge: ["30px", { lineHeight: "1", letterSpacing: "-1px" }],
        count: ["27px", { lineHeight: "1.05", letterSpacing: "-0.9px" }],
        tile: ["22px", { lineHeight: "1.1", letterSpacing: "-0.6px" }],
        supplier: ["17px", { lineHeight: "1.3" }],
        action: ["15px", { lineHeight: "1.35" }],
        body: ["14px", { lineHeight: "1.5" }],
        row: ["13px", { lineHeight: "1.45" }],
        meta: ["12px", { lineHeight: "1.4" }],
        chip: ["11px", { lineHeight: "1.3" }],
        micro: ["10px", { lineHeight: "1.2" }],
      },
      borderRadius: { card: "18px", input: "14px", panel: "12px", sheet: "22px" },
      spacing: { gutter: "16px", cardpad: "18px" },
      keyframes: {
        rise: { "0%": { opacity: 0, transform: "translateY(8px)" },
                "100%": { opacity: 1, transform: "translateY(0)" } },
        gpulse: { "0%": { boxShadow: "0 0 0 0 rgba(10,107,224,.45)" },
                  "70%": { boxShadow: "0 0 0 7px rgba(10,107,224,0)" },
                  "100%": { boxShadow: "0 0 0 0 rgba(10,107,224,0)" } },
        blink: { "0%,100%": { opacity: 0.25 }, "50%": { opacity: 1 } },
        wv: { "0%,100%": { transform: "scaleY(0.35)" },
              "50%": { transform: "scaleY(1)" } },
        sheetin: { "0%": { transform: "translateY(100%)" },
                   "100%": { transform: "translateY(0)" } },
        fade: { "0%": { opacity: 0 }, "100%": { opacity: 1 } },
      },
      animation: {
        rise: "rise .38s cubic-bezier(.2,.7,.3,1) both",
        gpulse: "gpulse 1.1s ease infinite",
        blink: "blink 1s ease infinite",
        wv: "wv .9s ease-in-out infinite",
        sheetin: "sheetin .28s cubic-bezier(.2,.8,.25,1) both",
        fade: "fade .2s ease both",
      },
    },
  },
  plugins: [],
};
